---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-cloudwatch
  namespace: fluentd-cloudwatch
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-cloudwatch
  template:
    metadata:
      labels:
        k8s-app: fluentd-cloudwatch
      annotations:
        configHash: 8915de4cf9c3551a8dc74c0137a3e83569d28c71044b0359c2578d2e0461825
    spec:
      nodeSelector:
        type: api-node
      serviceAccountName: fluentd-cloudwatch
      terminationGracePeriodSeconds: 30
      # Because the image's entrypoint requires to write on /fluentd/etc but we mount configmap there which is read-only,
      # this initContainers workaround or other is needed.
      # See https://github.com/fluent/fluentd-kubernetes-daemonset/issues/90
      initContainers:
        - name: copy-fluentd-config
          image: 174550113169.dkr.ecr.ap-southeast-2.amazonaws.com/docker-hub/busybox:1.35.0
          command: ['sh', '-c', 'cp /config-volume/..data/* /fluentd/etc']
          volumeMounts:
            - name: config-volume
              mountPath: /config-volume
            - name: fluentdconf
              mountPath: /fluentd/etc
        - name: update-log-driver
          image: 174550113169.dkr.ecr.ap-southeast-2.amazonaws.com/docker-hub/busybox:1.35.0
          command: ['sh','-c','']
      containers:
        - name: fluentd-cloudwatch
          image: 174550113169.dkr.ecr.ap-southeast-2.amazonaws.com/docker-hub/fluent/fluentd-kubernetes-daemonset:v1.14.6-debian-cloudwatch-1.1
          env:
            - name: GATEWAY_RETENTION_DAYS
              valueFrom:
                configMapKeyRef:
                  name: log-retention
                  key: logs.gateway.retention.days
            - name: APPLICATION_RETENTION_DAYS
              valueFrom:
                configMapKeyRef:
                  name: log-retention
                  key: logs.application.retention.days
            - name: SYSTEM_RETENTION_DAYS
              valueFrom:
                configMapKeyRef:
                  name: log-retention
                  key: logs.system.retention.days
            - name: CI_VERSION
              value: "k8s/1.2.1"
          volumeMounts:
            - name: config-volume
              mountPath: /config-volume
            - name: fluentdconf
              mountPath: /fluentd/etc
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: runlogjournal
              mountPath: /run/log/journal
              readOnly: true
            - name: dmesg
              mountPath: /var/log/dmesg
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-cloudwatch
        - name: fluentdconf
          emptyDir: {}
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: runlogjournal
          hostPath:
            path: /run/log/journal
        - name: dmesg
          hostPath:
            path: /var/log/dmesg
